#!/bin/bash

# Stop on any error
set -e
echo "--- Updating and Upgrading System ---"
sudo apt update
sudo apt upgrade -y

# Automatically restart outdated services during install process
echo "--- Configuring automatic service restarts ---"
sudo sed -i "/#\$nrconf{restart} = 'i';/s/.*/\$nrconf{restart} = 'a';/" /etc/needrestart/needrestart.conf

# Install gcc
echo "--- Installing GCC ---"
sudo apt install -y gcc

# Install cuda
echo "--- Installing CUDA Toolkit ---"
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
sudo dpkg -i cuda-keyring_1.1-1_all.deb
sudo apt-get update
sudo apt-get -y install cuda-toolkit-12-6
rm cuda-keyring_1.1-1_all.deb

# Install NVIDIA drivers
echo "--- Installing NVIDIA Drivers ---"
sudo apt-get install -y nvidia-open

# Install docker
echo "--- Installing Docker ---"

## Add Docker's official GPG key:
sudo apt-get install ca-certificates curl
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc

## Add the repository to Apt sources:
echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
         $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
         sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update

## Install packages
sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

## Add user to docker group
sudo usermod -aG docker "$USER"

# Installing NVIDIA container toolkit
echo "--- Installing NVIDIA Container Toolkit ---"
curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
        && curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
        sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
        sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
sudo apt-get update
sudo apt-get install -y nvidia-container-toolkit

## Add nvidia runtime
sudo nvidia-ctk runtime configure --runtime=docker
sudo systemctl restart docker


## Set up firewall
echo "--- Setting up Firewall (UFW) ---"
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

# Make docker work with ufw using the ufw-docker utility for robustness
echo "--- Installing ufw-docker utility to fix firewall compatibility ---"
sudo wget -O /usr/local/bin/ufw-docker https://github.com/chaifeng/ufw-docker/raw/master/ufw-docker
sudo chmod +x /usr/local/bin/ufw-docker
ufw-docker install

echo "--- Enabling and reloading firewall ---"
sudo ufw enable
sudo ufw reload

echo "--- Installation done. Please reboot the system for all changes to take effect. ---"