{
 "title": "svea1-2xH100",
 "description": "vLLM metrics for svea1-2xH100",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Requests being handled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "vllm:num_requests_running", "legendFormat": "Number of requests running" },
    { "expr": "vllm:num_requests_waiting", "legendFormat": "Number of requests waiting" }
   ]
  },
  {
   "title": "Generation tokens/s",
   "type": "timeseries",
   "description": "Speed of tokens/second in total over all requests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(vllm:avg_generation_throughput_toks_per_s[1m])",
     "legendFormat": "Generated tokens per second"
    }
   ]
  },
  {
   "title": "Time to First Token",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vllm:time_to_first_token_seconds_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "E2E Generation time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vllm:e2e_request_latency_seconds_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_UTIL", "legendFormat": "Usage % {{modelName}} #{{gpu}}" }
   ]
  }
 ]
}